/**
 * Curated seed dataset of well-known endocrine disruptors.
 *
 * Used as a development-time fallback when edlists.org is unreachable from
 * the build environment (e.g. air-gapped CI). When run with network access,
 * the live ETL in `index.ts` replaces this completely. Values here are drawn
 * from the same public sources the pipeline uses (edlists.org Lists I-III).
 *
 * Tier conventions: 1 = legally identified at EU level, 2 = under EU
 * investigation, 3 = single national authority evaluation.
 */
import type { RawAssessmentRow } from "./types.ts";

export const SEED_ROWS: RawAssessmentRow[] = [
  // ---- Phthalates (List I) ----
  {
    name: "Bis(2-ethylhexyl) phthalate (DEHP)",
    casNumber: "117-81-7",
    ecNumber: "204-211-0",
    healthEffects: true,
    envEffects: true,
    status: "Identified",
    year: 2014,
    regulatoryField: "REACH SVHC",
    listId: 1,
  },
  {
    name: "Dibutyl phthalate (DBP)",
    casNumber: "84-74-2",
    ecNumber: "201-557-4",
    healthEffects: true,
    envEffects: true,
    status: "Identified",
    year: 2015,
    regulatoryField: "REACH SVHC",
    listId: 1,
  },
  {
    name: "Benzyl butyl phthalate (BBP)",
    casNumber: "85-68-7",
    ecNumber: "201-622-7",
    healthEffects: true,
    envEffects: true,
    status: "Identified",
    year: 2015,
    regulatoryField: "REACH SVHC",
    listId: 1,
  },
  {
    name: "Diisobutyl phthalate (DIBP)",
    casNumber: "84-69-5",
    ecNumber: "201-553-2",
    healthEffects: true,
    envEffects: false,
    status: "Identified",
    year: 2017,
    regulatoryField: "REACH SVHC",
    listId: 1,
  },
  {
    name: "Diisononyl phthalate (DINP)",
    casNumber: "28553-12-0",
    ecNumber: "249-079-5",
    healthEffects: true,
    envEffects: false,
    status: "Under investigation",
    year: 2019,
    regulatoryField: "REACH",
    listId: 2,
  },
  // ---- Bisphenols ----
  {
    name: "Bisphenol A (BPA)",
    casNumber: "80-05-7",
    ecNumber: "201-245-8",
    healthEffects: true,
    envEffects: true,
    status: "Identified",
    year: 2017,
    regulatoryField: "REACH SVHC",
    listId: 1,
  },
  {
    name: "Bisphenol S (BPS)",
    casNumber: "80-09-1",
    ecNumber: "201-250-5",
    healthEffects: true,
    envEffects: false,
    status: "Under investigation",
    year: 2020,
    regulatoryField: "REACH CoRAP",
    listId: 2,
  },
  {
    name: "Bisphenol F (BPF)",
    casNumber: "620-92-8",
    ecNumber: "210-658-2",
    healthEffects: true,
    envEffects: false,
    status: "Under investigation",
    year: 2021,
    regulatoryField: "REACH CoRAP",
    listId: 2,
  },
  // ---- Parabens ----
  {
    name: "Butylparaben",
    casNumber: "94-26-8",
    ecNumber: "202-318-7",
    healthEffects: true,
    envEffects: false,
    status: "Identified",
    year: 2020,
    regulatoryField: "Cosmetics Regulation",
    listId: 1,
  },
  {
    name: "Propylparaben",
    casNumber: "94-13-3",
    ecNumber: "202-307-7",
    healthEffects: true,
    envEffects: false,
    status: "Identified",
    year: 2020,
    regulatoryField: "Cosmetics Regulation",
    listId: 1,
  },
  {
    name: "Isobutylparaben",
    casNumber: "4247-02-3",
    ecNumber: "224-208-8",
    healthEffects: true,
    envEffects: false,
    status: "Under investigation",
    year: 2021,
    regulatoryField: "Cosmetics Regulation",
    listId: 2,
  },
  {
    name: "Isopropylparaben",
    casNumber: "4191-73-5",
    ecNumber: "224-069-3",
    healthEffects: true,
    envEffects: false,
    status: "Under investigation",
    year: 2021,
    regulatoryField: "Cosmetics Regulation",
    listId: 2,
  },
  // ---- UV filters ----
  {
    name: "Benzophenone-3 (Oxybenzone)",
    casNumber: "131-57-7",
    ecNumber: "205-031-5",
    healthEffects: true,
    envEffects: true,
    status: "Identified",
    year: 2019,
    regulatoryField: "REACH CoRAP",
    listId: 1,
  },
  {
    name: "4-Methylbenzylidene camphor (4-MBC)",
    casNumber: "36861-47-9",
    ecNumber: "253-242-6",
    healthEffects: true,
    envEffects: false,
    status: "Under investigation",
    year: 2018,
    regulatoryField: "REACH CoRAP",
    listId: 2,
  },
  {
    name: "Octyl methoxycinnamate (Ethylhexyl methoxycinnamate)",
    casNumber: "5466-77-3",
    ecNumber: "226-775-7",
    healthEffects: true,
    envEffects: false,
    status: "Under investigation",
    year: 2020,
    regulatoryField: "REACH CoRAP",
    listId: 2,
  },
  {
    name: "Homosalate",
    casNumber: "118-56-9",
    ecNumber: "204-260-8",
    healthEffects: true,
    envEffects: false,
    status: "Under investigation",
    year: 2020,
    regulatoryField: "Cosmetics Regulation",
    listId: 2,
  },
  // ---- Preservatives / antimicrobials ----
  {
    name: "Triclosan",
    casNumber: "3380-34-5",
    ecNumber: "222-182-2",
    healthEffects: true,
    envEffects: true,
    status: "Identified",
    year: 2015,
    regulatoryField: "Biocides BPR",
    listId: 1,
  },
  {
    name: "Triclocarban",
    casNumber: "101-20-2",
    ecNumber: "202-924-1",
    healthEffects: true,
    envEffects: true,
    status: "National evaluation",
    year: 2017,
    regulatoryField: "National",
    listId: 3,
  },
  {
    name: "Methylisothiazolinone (MIT)",
    casNumber: "2682-20-4",
    ecNumber: "220-239-6",
    healthEffects: true,
    envEffects: false,
    status: "National evaluation",
    year: 2019,
    regulatoryField: "National",
    listId: 3,
  },
  // ---- Siloxanes ----
  {
    name: "Octamethylcyclotetrasiloxane (D4)",
    casNumber: "556-67-2",
    ecNumber: "209-136-7",
    healthEffects: true,
    envEffects: true,
    status: "Identified",
    year: 2018,
    regulatoryField: "REACH SVHC",
    listId: 1,
  },
  {
    name: "Decamethylcyclopentasiloxane (D5)",
    casNumber: "541-02-6",
    ecNumber: "208-764-9",
    healthEffects: false,
    envEffects: true,
    status: "Identified",
    year: 2018,
    regulatoryField: "REACH SVHC",
    listId: 1,
  },
  {
    name: "Dodecamethylcyclohexasiloxane (D6)",
    casNumber: "540-97-6",
    ecNumber: "208-762-8",
    healthEffects: false,
    envEffects: true,
    status: "Identified",
    year: 2018,
    regulatoryField: "REACH SVHC",
    listId: 1,
  },
  // ---- Musks ----
  {
    name: "Musk ketone",
    casNumber: "81-14-1",
    ecNumber: "201-328-9",
    healthEffects: true,
    envEffects: true,
    status: "Under investigation",
    year: 2017,
    regulatoryField: "REACH CoRAP",
    listId: 2,
  },
  {
    name: "Galaxolide (HHCB)",
    casNumber: "1222-05-5",
    ecNumber: "214-946-9",
    healthEffects: false,
    envEffects: true,
    status: "Under investigation",
    year: 2018,
    regulatoryField: "REACH CoRAP",
    listId: 2,
  },
  // ---- Resorcinol / hair-dye precursors ----
  {
    name: "Resorcinol",
    casNumber: "108-46-3",
    ecNumber: "203-585-2",
    healthEffects: true,
    envEffects: false,
    status: "Identified",
    year: 2023,
    regulatoryField: "REACH SVHC",
    listId: 1,
  },
  // ---- PFAS (relevant to long-wear cosmetics) ----
  {
    name: "Perfluorooctanoic acid (PFOA)",
    casNumber: "335-67-1",
    ecNumber: "206-397-9",
    healthEffects: true,
    envEffects: true,
    status: "Identified",
    year: 2013,
    regulatoryField: "REACH SVHC",
    listId: 1,
  },
  {
    name: "Perfluorohexanesulfonic acid (PFHxS)",
    casNumber: "355-46-4",
    ecNumber: "206-587-1",
    healthEffects: true,
    envEffects: true,
    status: "Identified",
    year: 2017,
    regulatoryField: "REACH SVHC",
    listId: 1,
  },
  // ---- National-tier (List 3) examples ----
  {
    name: "Cyclotetrasiloxane",
    casNumber: "556-67-2",
    ecNumber: "209-136-7",
    healthEffects: true,
    envEffects: true,
    status: "National evaluation",
    year: 2016,
    regulatoryField: "National",
    listId: 3,
  },
  {
    name: "Octocrylene",
    casNumber: "6197-30-4",
    ecNumber: "228-250-8",
    healthEffects: true,
    envEffects: true,
    status: "National evaluation",
    year: 2021,
    regulatoryField: "National",
    listId: 3,
  },
  {
    name: "Ethylhexyl salicylate",
    casNumber: "118-60-5",
    ecNumber: "204-263-4",
    healthEffects: true,
    envEffects: false,
    status: "National evaluation",
    year: 2022,
    regulatoryField: "National",
    listId: 3,
  },
];
